### ISSUE TITLE
Printer Test Page shows Ubuntu logo

### ISSUE THREAD

**Issue by sez11a** [netrunner-kubuntu-legacy/netrunner-feedback#15]
Noticed today when adding a printer that the printer test page shows the Ubuntu logo. Makes sense, since Netrunner is based on Kubuntu, but I was thinking this might be something you'd want to customize.

**Comment by shadeslayer** [comment]
Comes from <code>/usr/share/cups/data/default-testpage.pdf</code>
Needs relevant artwork in order to replace, in addition to make a custom cups package. While this introduces extra overheads ( packaging a custom cups ) , I'd be happy to replace the artwork if I get the proper PDF and the go ahead from @star-buck
